services:
  dr_halimova_bot:
    build: .
    container_name: dr_halimova_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"